-- 000001: Lookup tables - core reference data
-- All tables in 3NF, no foreign key dependencies

CREATE TABLE IF NOT EXISTS ROLE (
  role_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  role_code TEXT NOT NULL UNIQUE,
  role_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ACCOUNT_STATUS (
  account_status_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  status_code TEXT NOT NULL UNIQUE,
  status_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SEX (
  sex_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  sex_code TEXT NOT NULL UNIQUE,
  sex_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ACTIVITY_LEVEL (
  activity_level_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  activity_code TEXT NOT NULL UNIQUE,
  activity_name TEXT NOT NULL,
  multiplier NUMERIC(4,3) NOT NULL CHECK (multiplier >= 1.0 AND multiplier <= 2.5)
);

CREATE TABLE IF NOT EXISTS FITNESS_GOAL (
  fitness_goal_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  goal_code TEXT NOT NULL UNIQUE,
  goal_name TEXT NOT NULL,
  description TEXT,
  CONSTRAINT fitness_goal_code_check CHECK (goal_code <> 'meal_plan')
);

CREATE TABLE IF NOT EXISTS MEAL_TYPE (
  meal_type_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  meal_type_code TEXT NOT NULL UNIQUE,
  meal_type_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS LOG_SOURCE (
  log_source_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  source_code TEXT NOT NULL UNIQUE,
  source_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MEAL_PLAN_STATUS (
  status_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  status_code TEXT NOT NULL UNIQUE,
  status_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ALLERGY (
  allergy_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  allergy_name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS DIETARY_RESTRICTION (
  restriction_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  restriction_name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS FOOD_CATEGORY (
  category_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  category_name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS DATA_SOURCE (
  source_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  source_name TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_reference TEXT
);

CREATE TABLE IF NOT EXISTS NUTRITION_FORMULA_VERSION (
  formula_version_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  version_code TEXT NOT NULL UNIQUE,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS AI_SCAN_STATUS (
  scan_status_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  status_code TEXT NOT NULL UNIQUE,
  status_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAT_ROLE (
  chat_role_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  role_code TEXT NOT NULL UNIQUE,
  role_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAT_SAFETY_STATUS (
  safety_status_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  status_code TEXT NOT NULL UNIQUE,
  status_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAT_DELIVERY_STATUS (
  delivery_status_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  status_code TEXT NOT NULL UNIQUE,
  status_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS REPORT_REASON (
  reason_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  reason_code TEXT NOT NULL UNIQUE,
  reason_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS REPORT_STATUS (
  status_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  status_code TEXT NOT NULL UNIQUE,
  status_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MODERATION_ACTION_TYPE (
  action_type_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  action_code TEXT NOT NULL UNIQUE,
  action_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SYNC_ENTITY_TYPE (
  sync_entity_type_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  entity_code TEXT NOT NULL UNIQUE,
  entity_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SYNC_OPERATION_TYPE (
  sync_operation_type_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  operation_code TEXT NOT NULL UNIQUE,
  operation_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SYNC_STATUS (
  sync_status_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  status_code TEXT NOT NULL UNIQUE,
  status_name TEXT NOT NULL
);
